--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: http
  name: demo-app
  namespace: sock-shop
spec:
  ingressClassName: nginx
  rules:
  - host: namix.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port: 
              number: 80
---
